// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action_state.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActionRequestByIdempotencyKey = `-- name: GetActionRequestByIdempotencyKey :one
select id, tenant_id, request_fingerprint, created_at
from action_requests
where tenant_id = $1 and idempotency_key = $2
`

type GetActionRequestByIdempotencyKeyParams struct {
	TenantID       pgtype.UUID
	IdempotencyKey []byte
}

type GetActionRequestByIdempotencyKeyRow struct {
	ID                 pgtype.UUID
	TenantID           pgtype.UUID
	RequestFingerprint []byte
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) GetActionRequestByIdempotencyKey(ctx context.Context, arg GetActionRequestByIdempotencyKeyParams) (GetActionRequestByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getActionRequestByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i GetActionRequestByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequestFingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const getActionState = `-- name: GetActionState :one
select action_request_id, tenant_id, state, version, lease_owner, lease_expires_at, updated_at
from action_state
where action_request_id = $1
`

func (q *Queries) GetActionState(ctx context.Context, actionRequestID pgtype.UUID) (ActionState, error) {
	row := q.db.QueryRow(ctx, getActionState, actionRequestID)
	var i ActionState
	err := row.Scan(
		&i.ActionRequestID,
		&i.TenantID,
		&i.State,
		&i.Version,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnsealedAuditEvents = `-- name: ListUnsealedAuditEvents :many
select id, tenant_id, stream_id, ingest_seq, action_request_id, event_type,
       attested_by, metadata, recorded_at
from audit_events
where tenant_id = $1 and stream_id = $2 and epoch_id is null and ingest_seq <= $3
order by ingest_seq
`

type ListUnsealedAuditEventsParams struct {
	TenantID  pgtype.UUID
	StreamID  pgtype.UUID
	IngestSeq pgtype.Int8
}

type ListUnsealedAuditEventsRow struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	StreamID        pgtype.UUID
	IngestSeq       pgtype.Int8
	ActionRequestID pgtype.UUID
	EventType       string
	AttestedBy      string
	Metadata        []byte
	RecordedAt      pgtype.Timestamptz
}

func (q *Queries) ListUnsealedAuditEvents(ctx context.Context, arg ListUnsealedAuditEventsParams) ([]ListUnsealedAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listUnsealedAuditEvents, arg.TenantID, arg.StreamID, arg.IngestSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnsealedAuditEventsRow
	for rows.Next() {
		var i ListUnsealedAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StreamID,
			&i.IngestSeq,
			&i.ActionRequestID,
			&i.EventType,
			&i.AttestedBy,
			&i.Metadata,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
