// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActionRequest struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	AgentID                string
	SessionID              pgtype.UUID
	IdempotencyKey         []byte
	RequestFingerprint     []byte
	ToolName               string
	ToolParams             []byte
	Environment            string
	CorrelationID          pgtype.UUID
	ParentActionID         pgtype.UUID
	PolicyVersionEvaluated int64
	CreatedAt              pgtype.Timestamptz
}

type ActionResult struct {
	ActionRequestID  pgtype.UUID
	TenantID         pgtype.UUID
	Status           string
	OutputRef        pgtype.Text
	Error            pgtype.Text
	SideEffects      []byte
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	ReceiptSignature []byte
}

type ActionState struct {
	ActionRequestID pgtype.UUID
	TenantID        pgtype.UUID
	State           string
	Version         int32
	LeaseOwner      pgtype.Text
	LeaseExpiresAt  pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ApprovalCallbackToken struct {
	TokenHash         []byte
	TenantID          pgtype.UUID
	ApprovalRequestID pgtype.UUID
	ExpiresAt         pgtype.Timestamptz
	UsedAt            pgtype.Timestamptz
}

type ApprovalDecision struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	ApprovalRequestID pgtype.UUID
	ApproverID        string
	Decision          string
	Reason            pgtype.Text
	DecidedAt         pgtype.Timestamptz
}

type ApprovalRequest struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	ActionRequestID pgtype.UUID
	ApproverTarget  string
	Status          string
	Version         int32
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type AuditEpoch struct {
	EpochID       pgtype.UUID
	TenantID      pgtype.UUID
	StreamID      pgtype.UUID
	FirstSequence int64
	LastSequence  int64
	RootHash      []byte
	PrevEpochRoot []byte
	Signature     []byte
	KeyID         string
	AnchoredAt    pgtype.Timestamptz
	SealedAt      pgtype.Timestamptz
}

type AuditEvent struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	StreamID          pgtype.UUID
	IngestSeq         pgtype.Int8
	ActionRequestID   pgtype.UUID
	EventType         string
	AttestedBy        string
	Metadata          []byte
	DecisionRef       pgtype.UUID
	RedactedInputsRef pgtype.UUID
	Refs              []byte
	RecordedAt        pgtype.Timestamptz
	SequenceNumber    pgtype.Int8
	PreviousHash      []byte
	EventHash         []byte
	EpochID           pgtype.UUID
}

type ConfigurationSnapshot struct {
	TenantID    pgtype.UUID
	Version     int64
	Content     []byte
	ContentHash []byte
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
}

type ExecutionGrant struct {
	GrantID           pgtype.UUID
	TenantID          pgtype.UUID
	ActionRequestID   pgtype.UUID
	ParamsHash        []byte
	KeyID             string
	ExpiresAt         pgtype.Timestamptz
	IssuedAt          pgtype.Timestamptz
	ReceiptReceivedAt pgtype.Timestamptz
}

type PolicyDecision struct {
	ID                 pgtype.UUID
	TenantID           pgtype.UUID
	ActionRequestID    pgtype.UUID
	Decision           string
	RiskClassification string
	MatchedRuleID      string
	EvaluationTrace    []byte
	PolicyVersion      int64
	EvaluatedAt        pgtype.Timestamptz
}

type ReconciliationResult struct {
	ActionRequestID pgtype.UUID
	TenantID        pgtype.UUID
	OperatorID      string
	VerifiedOutcome string
	EvidenceRef     pgtype.Text
	ReconciledAt    pgtype.Timestamptz
}

type RedactedActionInput struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	ActionRequestID pgtype.UUID
	RedactedParams  []byte
	CreatedAt       pgtype.Timestamptz
}
